name: Build Image

on:
  workflow_call:
    inputs:
      has-docker-image:
        required: true
        type: boolean
      images:
        required: true
        type: string

    secrets:
      docker-password:
        required: true
      docker-username:
        required: true

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: inputs.has-docker-image
    steps:
      - name: test 
        run: echo "Building Docker image as docker-image.yml with images key was found"

      - name: Debug Inputs
        run: |
          echo "has-docker-image: ${{ inputs.has-docker-image }}"
          echo "docker-username: ${{ secrets.docker-username }}"
          echo "docker-password: ${{ secrets.docker-password }}"
          echo "images: ${{ inputs.images }}"

      - name: Login to ACR
        if: ${{ secrets.docker-username }} != '' && ${{ secrets.docker-password }} != ''
        run: |
          if [ -z "${{ fromJSON(inputs.images)[0].registry }}" ]; then
            echo "Registry not found in docker-image.yml, skipping"
            exit 0
          fi
          echo "${{ secrets.docker-password }}" | docker login -u "${{ secrets.docker-username }}" \
                  --password-stdin "${{ fromJSON(inputs.images)[0].registry }}"