name: Build Image

on:
  workflow_call:
    inputs:
      has-docker-image:
        required: true
        type: string
      docker-username:
        required: true
        type: string
      docker-password:
        required: true
        type: string
      images:
        required: true
        type: string

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: ${{ inputs.has-docker-image == 'true' }}
    steps:
      - name: test 
        run: echo "Building Docker image as docker-image.yml with images key was found"

      - name: Login to ACR
        if: inputs.DOCKER_ALICLOUD_USERNAME != '' && inputs.DOCKER_ALICLOUD_PASSWORD != ''
        run: |
          if [ -z "${{ fromJSON(inputs.images)[0].registry }}" ]; then
            echo "Registry not found in docker-image.yml, skipping"
            exit 0
          fi
          echo "$inputs.DOCKER_ALICLOUD_PASSWORD" | docker login -u "$inputs.DOCKER_ALICLOUD_USERNAME" \
                  --password-stdin "${{ fromJSON(inputs.images)[0].registry }}"