name: CI:Test Actions Workflows
run-name: >-
  ${{ github.event_name == 'pull_request' && format('PR #{0} CI Test Actions Workflows', github.event.number) }}

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  CICD:
    name: Run shift-left and Deploy Workflows
    uses: ./.github/workflows/shift-left.yml
    with:
      acr-name: "test-acr-name"
      run-number: ${{ github.event.number }}

  test-docker-images:
    needs: CICD
    if: needs.CICD.outputs.has-docker-image == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test-docker-images ${{ needs.CICD.outputs.has-docker-image }}"
